### ISSUE TITLE
configure script doesn't work on macOS because of severely limited getopt

### ISSUE THREAD

**Issue by Kristine1975** [rsta2/circle#254]
On macOS 10.14.6, I downloaded Circle release 44.1, unpacked ZIP archive and in the resulting folder executed `./configure -h` to see the available options. I got: `Error: Invalid toolchain prefix: arm-none-eabi-`.

This is because macOS's `getopt` is severely limited: it has no options of any kind (no `-o`, `--long`, `-n`), so parsing the command line simply doesn't work correctly. Thus the script doesn't show the help as intended, but actually performs the configuration (which fails because I use clang as a cross-compiler, not the ARM-provided gcc).

I don't know how it would be possible to fix this except by requiring GNU's `getopt` to be installed (for example through Homebrew, `brew install gnu-getopt`), so this is more a PR for the Readme file.

**Comment by rsta2** [comment]
Circle can be built on Linux and Windows. Unfortunately I'm not a aware of anybody building it on macOS. While `configure` shouldn't be a big problem, because the *Config.mk* file can be created manually, *clang* is not supported too. I made an attempt to support *clang* using a Linux host earlier, but wasn't able to build a working 64-bit binary with it. Currently GNU C/C++ is the only supported compiler.

**Comment by Kristine1975** [comment]
For some reason I just assumed that Circle can be built on macOS. I'm sorry for wasting your time.

**Comment by rsta2** [comment]
No problem.
