### ISSUE TITLE
Cherry USB Keyboard problems with sample project

### ISSUE THREAD

**Issue by XORElectronics** [rsta2/circle#255]
Hello, 
I try to use a Cherry G84-4100 USB Keyboard with a RPI zero and the USBKeyboard sample project. (latest 44.1)
It doesn't work (either on power up or hotplug.) However, in combination with a Hub it works fine.

The errors i get are the following:
dwhci: Transaction failed (status 0x82)
usbdev0-1: Cannot get device descriptor (short)
dwhci: Cannot initialize root port
And then multiple:
dwroot: Previous attempt to initialize device failed. 

From here it is also not recovering and even if I plug in another working USB keyboard it fails with this last message:
dwroot: Previous attempt to initialize device failed. 
A power reset is needed from here.

Is there anything I can do so it would work also without a hub? 

Thanks!

**Comment by rsta2** [comment]
I'm afraid you cannot do much and maybe this keyboard has to be added to the list of [Not compatible devices](https://github.com/rsta2/circle/wiki/Device-compatibility-list#not-compatible-devices). The reported error (Transaction failed (status 0x82)) is a USB transaction error, which is probably caused by timing incompatibilities of the Circle USB DWHCI driver with this device. The Circle driver works with most but not all devices.

You could try to disable the [USE_USB_SOF_INTR](https://github.com/rsta2/circle/blob/master/include/circle/sysconfig.h#L203) option for a test to get a different timing, but it's not sure, if this helps and you may run into other problems with USB plug-and-play and REALTIME then.
