### ISSUE TITLE
TLB dirty after loading image with u-boot and PI B+

### ISSUE THREAD

**Issue by jsanchezv** [rsta2/circle#26]
When a bare image is loaded using u-boot the TLB cache maintains contents that generate problems when MMU is reenabled by Circle. This can be tested using sample 03-screentext, that shows strange lines over the text at random places, and last lines completely shattered when the screen resolution is low, as 640x480. When the MMU is disabled (calling memory(FALSE) in kernel.cpp constructor) all screen is showed correctly.

As specified in ARM Cortex-A Series Programmer's Guide (DEN0013D), section 8.8, after disable MMU is needed to invalidate L1-Cache, TLB and branch predictor (point 2 from sample code). For this issue the relevant action is invalidate TLB, that resolves the problem.

I've modified the file startup.S as:

mov	r0, #0
mcr	p15, 0, r0, c12, c0, 0  /* reset VBAR (if changed by u-boot) */
mcr p15, 0, r0, c7, c5, 0     /* Invalidate Instruction Cache */
mcr p15, 0, r0, c7, c5, 6     /* Invalidate branch prediction array */
mcr p15, 0, r0, c8, c7, 0     /* Invalidate entire Unified Main TLB */
mcr p15, 0, r0, c7, c5, 4     /* need to be changed for ISB instruction on PI-2/3 */

**Comment by rsta2** [comment]
I have pushed an update which includes your solution. I have inserted it into the MMU initialization code at CMemorySystem::EnableMMU() where it belongs to in my opinion and where I can use the macros from *synchronize.h*. I added a DataSyncBarrier() because it ensures (according to the ARMv6 ARM) that the invalidation of the unified TLB is completed. I have tested it with u-boot.

Thanks for finding and solving this problem!
